name: Generate Sitemap

on:
  push:
    branches: [main]
    paths-ignore:
      - 'sitemap.xml'  # Prevent recursive triggers
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://bytexgrid.github.io/awesome-list-explorer/
          include-html: true
          include-pdf: false
          include-images: true
          additional-extensions: md
          exclude-paths: .github,.git

      - name: Configure Git
        if: steps.sitemap.outputs.sitemap-path != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push if changed
        if: steps.sitemap.outputs.sitemap-path != ''
        run: |
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update sitemap.xml [$(date +'%Y-%m-%d')]" && git push)